[[headers]]
  for = "/*"
  [headers.values]
    Expect-CT = "max-age=86400"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "max-age=86400"

    Content-Security-Policy = """
      base-uri 'self';
      connect-src 'self' api.github.com www.google-analytics.com;
      default-src 'self' www.google-analytics.com;
      form-action 'self';
      frame-src 'self' onedrive.live.com;
      img-src 'self' data: www.google-analytics.com;
      manifest-src 'self';
      script-src 'self' 'unsafe-inline' www.google-analytics.com;
      style-src 'self' 'unsafe-inline';
    """

    Feature-Policy = """
      accelerometer 'none';
      ambient-light-sensor 'none';
      autoplay 'none';
      battery 'none';
      camera 'none';
      display-capture 'none';
      document-domain 'none';
      encrypted-media 'none';
      execution-while-out-of-viewport 'self';
      fullscreen 'self';
      geolocation 'none';
      gyroscope 'none';
      layout-animations 'self';
      legacy-image-formats 'self';
      microphone 'none';
      midi 'none';
      navigation-override 'none';
      oversized-images 'none';
      payment 'none';
      picture-in-picture 'none';
      publickey-credentials-get 'none';
      sync-xhr 'self';
      usb 'none';
      wake-lock 'none';
      xr-spatial-tracking 'none'
    """

[build]
  functions = "functions"
